# Snapshot Baseline - Auto-generated by r-package-cleanup
# Date: 2026-01-29

test_that("us_baby_names returns data.frame for each type", {
  skip_if_offline()
  skip_on_cran()

  # Snapshot: national type returns data.frame
  expect_s3_class(
    us_baby_names(type = "national"),
    "data.frame"
  )

  # Snapshot: state type returns data.frame
  expect_s3_class(
    us_baby_names(type = "state"),
    "data.frame"
  )

  # Snapshot: territory type returns data.frame
  expect_s3_class(
    us_baby_names(type = "territory"),
    "data.frame"
  )
})

test_that("us_baby_names with multiple types returns data", {
  skip_if_offline()
  skip_on_cran()

  result <- us_baby_names(type = c("national", "state"))
  expect_s3_class(result, "data.frame")
})
